# Generated by Django 3.1.6 on 2021-04-12 09:59

import richtext.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210226_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=richtext.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='needs',
            field=richtext.fields.RichTextField(null=True),
        ),
    ]
