# Generated by Django 3.1.6 on 2021-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pin_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
