# Generated by Django 3.1.6 on 2021-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210422_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lat',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lon',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
