# Generated by Django 3.1.6 on 2021-04-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210423_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='lon',
            new_name='longitude',
        ),
    ]
